name: git_actions_ops

env:
  REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  REG_USERNAME: ${{ secrets.REG_USERNAME }}
  NAME: git_actions_ops

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: git_actions_ops

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Get current date
      run: echo "::set-output name=date::$(date +'%y%m%d%H%m')"
      id: date

    - name: Java build
      run: /usr/lib/apache-maven-3.6.3/bin/mvn clean package -DskipTests=true -e

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: $REG_USERNAME/git_actions_ops:latest, $REG_USERNAME/git_actions_ops:${{ steps.date.outputs.date }}
        file: ./Dockerfile
